### ISSUE TITLE
Error if glyph has no unicode value

### ISSUE THREAD

**Issue by benwiggy** [knutnergaard/FontLab-Scripts#1]
The set_smufl_names.py script stops with an error if `glyph.unicodes` returns a `NoneType` object.

This can be easily fixed with `if glyphs.unicode:` before line 31, and indenting the following lines.

**Comment by knutnergaard** [comment]
Thanks for spotting this, Ben!

**Comment by knutnergaard** [comment]
Just looked at this, and couldn't replicate the error. There's already a conditional in the relevant block at line 32, which should serve the same purpose.

Could there be something else going on?

**Comment by benwiggy** [comment]
I was getting this error, and my solution fixed it:

Traceback (most recent call last):
  File "/Users/Ben/Library/Application Support/FontLab/FontLab 7/Scripts/set_smufl_names.py", line 51, in <module>
    set_glyph_note_to_smufl_name(glyph)
  File "/Users/Ben/Library/Application Support/FontLab/FontLab 7/Scripts/set_smufl_names.py", line 31, in set_glyph_note_to_smufl_name
    for codepoint in glyph.unicodes:
TypeError: 'NoneType' object is not iterable

**Comment by knutnergaard** [comment]
Thank you!

I didn't realise you were talking about FL7, which I thought was a lost cause with regard to the note field.

Anyway, fixed in https://github.com/knutnergaard/FontLab-Scripts/commit/8cd332daefe69a6748039637347dfdc7f7c1e4ef#diff-5c1129d0b8a05269bdbfd78a064ca4d7ecfce738df92ed0cba64cabe57c5ebe8
